# Site settings
title: Mailbox2
email: mailboxapp2@gmail.com
description: Mailbox2 - Go trough your mailbox in seconds again. iPhone app to cleanup your inbox in seconds.
#baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://mailbox2app.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
