# Site settings
title: Mailbox2
email: mailboxapp2@gmail.com
description: Mailbox2 - Go trough your mailbox in seconds again. iPhone app to keep your inbox clean.
#baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.mailbox2app.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
